export class acervo {
    palavras: string[] = [
        "livro", "praia", "forno", "canoa", "pente", "tigre", "zebra", "cobra", "papel", "piano",
        "dança", "samba", "marca", "banda", "canto", "drama", "filme", "lente", "rosto", "vozes",
        "lugar", "chuva", "calor", "outro", "norte", "leste", "oeste", "praça", "lagoa", "monta",
        "musgo", "mouse", "mundo", "mural", "micro", "macro", "metro", "motor", "manga", "março",
        "abril", "agora", "amigo", "ativo", "atual", "aviso", "anexo", "baixo", "brisa", "banco",
        "brasa", "bruto", "brava", "beijo", "beira", "coisa", "caixa", "cante", "campo", "germe",
        "comer", "copia", "cobre", "cacau", "chama", "chave", "chefe", "corre", "corpo", "cores",
        "cravo", "crise", "dente", "dores", "dizer", "dobra", "dublo", "dedos", "deixa", "edema",
        "facas", "farol", "falar", "feira", "feliz", "ficar", "finge", "força", "forma", "fraco",
        "freio", "fugir", "fumar", "geral", "gosto", "grana", "gemer", "grito", "gruta", "golfe",
        "hotel", "hidra", "haste", "imune", "irado", "itens", "jazem", "jurar", "jazia", "junto",
        "jogos", "jipes", "jumbo", "juizo", "javas", "juras", "jurar", "jurar", "jurar", "gizar",
        "latas", "longo", "lugar", "luzes", "lutar", "lutam", "limpo", "lince", "jarra", "gigas",
        "lutam", "lugar", "ligar", "lados", "lapso", "lados", "louco", "lusco", "mimos", "gazua",
        "meios", "melas", "moeda", "minta", "março", "mesmo", "mesas", "modos", "muito", "grude",
        "marca", "muita", "musgo", "muito", "metro", "mexer", "muros", "musas", "notas", "grava",
        "norte", "naves", "nomes", "notas", "nuvem", "nasal", "nesta", "nadar", "nossa", "naval",
        "nuvem", "olhos", "ordem", "outro", "outra", "ouvir", "haver", "hiato", "horas", "ileso",
        "oxida", "obeso", "ovnis", "oxida", "argil", "jeito", "jogar", "julho", "junho", "jaula",
        "ovnis", "abrir", "autor", "barco", "beber", "bolha", "borda", "braço", "bruxa", "jegue",
        "burro", "calça", "clima", "curso", "curto", "disco", "estar", "filho", "final", "folha",
        "fruta", "gente", "girar", "globo", "graça", "homem", "horta", "humor", "ideal", "adiar",
        "algar", "amado", "anuir", "aonde", "apelo", "argil", "arroz", "assar", "azeri", "babar",
        "bagre", "banho", "bicho", "bolor", "bulir", "cansa", "chato", "choro", "chulo", "claro",
        "corte", "curar", "deixo", "dogma", "duque", "enfim", "estou", "exame", "fardo", "farto",
        "fatal", "fogue", "fundo", "gaita", "gasto", "geada", "gelar", "gueto", "honra", "idade",
        "ideia", "igual", "isola", "janta", "jovem", "largo", "laser", "leite", "lento", "lerdo",
        "levar", "lidar", "lindo", "longe", "magro", "maior", "malte", "manto", "matar", "meigo",
        "moita", "molho", "morno", "morro", "motim", "naipe", "nasci", "natal", "ninar", "nobre",
        "noite", "ombro", "ossos", "palma", "pardo", "passe", "peito", "perdo", "perto", "pezar",
        "picar", "pilar", "pingo", "pista", "poder", "prado", "prato", "prazo", "preço", "prima",
        "primo", "pular", "quero", "quota", "raiva", "rampa", "rango", "reais", "reino", "rezar",
        "risco", "roçar", "roubo", "russo", "saber", "sacar", "salto", "santo", "selar", "selos",
        "senso", "serra", "servo", "sexta", "sinal", "sobra", "sobre", "sorte", "subir", "sujei",
        "sujos", "talha", "tanga", "tarde", "tempo", "tenho", "terço", "terra", "tocar", "lacre",
        "laico", "larva", "lasca", "laura", "lavra", "leigo", "leito", "seiva", "fogue", "azeri",
        "lenho", "leque", "lesma", "libra", "limbo", "lisar", "lista", "logar", "lombo", "lotes",
        "louca", "louro", "macio", "maçom", "malha", "maria", "marra", "marta", "medir", "menta",
        "menti", "miado", "milho", "minar", "minha", "miolo", "mirar", "mitos", "molde", "monar",
        "monja", "moral", "morar", "morda", "morfo", "morte", "mosca", "mosco", "mudar", "mular",
        "mulas", "extra", "falta", "feixe", "festa", "feudo", "fiapo", "fibra", "ficha", "firma",
        "fisco", "fisga", "fluir", "forte", "frade", "friso", "frito", "fugaz", "furor", "furto",
        "fuzil", "gabar", "galho", "ganho", "garoa", "garra", "garro", "garvo", "gaupe",


    ];

}
